### PR TITLE
Bump versions of aws-sdk-go and stretchr-testify

### PR DESCRIPTION
**Pull request by lfaraone**
Now matching the versions packaged in Debian, updating the tests
accordingly to match a new field included in expected test output.

### CODE REVIEW

**Comment by barnybug** [comment]
The dependencies are vendored with dep - so vendor and the lock file should updated too. Aside - what's the reason for needing to update them?

**Comment by lfaraone** [comment]
@barnybug: Apologies, Go isn't a language I commonly work in. Pushed up the relevant changes in a separate commit. 

Also included the actual testcase change I made :) 

I was looking to package `cli53` for Debian, but the package failed to build due to a change in the output of the AWS SDK.

**Comment by barnybug** [comment]
Hi, cli53 should be built using the vendored libraries within cli53 github repo.

**Comment by lfaraone** [comment]
I realise, but we can't do that in Debian proper :) For context, I'm a Debian developer. 

I'm referring to including `cli53` as an installable Debian package in the Debian archive, not simply installing `cli53` *on* a Debian system. 

Any Go package we include is built against the various `golang-*-dev` packages in the archive. In this case, Debian's version of `aws-sdk-go` is newer, so the test suite fails without the enclosed patch.

**Comment by barnybug** [comment]
Ok, I'd be willing to make this change once, but doesn't this effectively tie cli53 into whatever Debian chooses to ship, forever more in order to remain packaged?

I can't see a great advantage to being installable as a Debian package, when it is downloadable as a single binary (for a much larger variety of platforms too).

**Comment by lfaraone** [comment]
> Ok, I'd be willing to make this change once, but doesn't this effectively tie cli53 into whatever Debian chooses to ship, forever more in order to remain packaged?

Well, no. If we move a library forward, I'll have to fix the breakage in Debian. We'll take it as a local patch, as [I've already done so for this issue](https://salsa.debian.org/lfaraone/cli53-dpkg/blob/master/debian/patches/001-fix-awscli-test). You always have the option of rejecting patches :)

> I can't see a great advantage to being installable as a Debian package, when it is downloadable as a single binary (for a much larger variety of platforms too).

It's sort of similar to the benefits of being available in Homebrew, but we make a few more commitments to our users that they appreciate beyond mere convenience… for example, part of the reason we try to avoid vendoring dependencies is to ensure we, the distribution, can quickly provide security updates for all dependant packages.

We also say "okay, this software is now in `stable`, it will continue to work *and its behaviour will not change* over the course of the release, save for bug fixes and security updates." People can choose to follow all their upstream projects and download from them directly, or instead from a Linux distribution if they want to know that _that version_ is supported for the duration of their Linux distribution's lifecycle.

**Comment by barnybug** [comment]
Ok, thanks for the detailed explanation. The policy does lead to upstream developers having to treat Debian as a special case though.

eg. I ship a binary release to 7 different platforms, plus Archlinux and homebrew packages and I can be sure they'll all using exactly the same, well tested and understood dependencies. And then Debian is an odd case of different dependencies that I've never necessarily tested it with (and I'd have to go to special effort to check what they are) - if every distribution followed the Debian model, I can't see how it wouldn't lead to a nightmare to manage for upstream.

But anyway... merging the PR :-)

**Comment by barnybug** [comment]
Sorry, I've had to revert this one as the integration tests show some failures. I don't think we can say the library update doesn't introduce other issues - may impact your choice on forcing the upgrade in the Debian package.

**Pull request merged**
