### PR TITLE
add rrcreate --append

### PR DESCRIPTION
**Pull request by flyinprogrammer**
sometimes it's nice to attach new records to record sets without having to know all the existing records.

### CODE REVIEW

**Comment by barnybug** [comment]
Thanks for your contribution.

Some minor changes I'd suggest:

- I think calling the parameter `--append`, sits more naturally alongside `--replace`
- it'd be good if createArgs validate() had a check for both `--append` and `--replace` - passing both wouldn't make much sense, so should be prevented
- the test description "Scenario: I can replace a resource record" needs updating
- for the tests I think a case for both the situations where the record already exists, and also for when the record does not previously exist would be worth writing

**Comment by barnybug** [comment]
Also one more - changing the action to UPSERT, changes existing behaviour on rrcreate with an existing record - before it would prevent this action, now it will overwrite without a warning. Dangerous - I don't think this behaviour should change.

**Comment by flyinprogrammer** [comment]
>Also one more - changing the action to UPSERT, changes existing behaviour on rrcreate with an existing record - before it would prevent this action, now it will overwrite without a warning. Dangerous - I don't think this behaviour should change.

would you be opposed to an `rrupsert` ?

**Comment by barnybug** [comment]
I think 'rrupsert' is the same as 'rrcreate --replace' (other than semantics of whether the server/client is implementing it)?

**Comment by barnybug** [comment]
For this change, I think you just need to enable the delete change for appends too, then the other action need not change.

**Comment by flyinprogrammer** [comment]
agreed! i have code coming here in a second

**Comment by flyinprogrammer** [comment]
> it'd be good if createArgs validate() had a check for both --append and --replace - passing both wouldn't make much sense, so should be prevented

and

> for the tests I think a case for both the situations where the record already exists, and also for when the record does not previously exist would be worth writing


i forgot - hold on.

**Comment by barnybug** [comment]
Great work, thanks!

**Pull request merged**
