### PR TITLE
Improvements for the handling of failover resource record sets

### PR DESCRIPTION
**Pull request by ankon**

### CODE REVIEW

**Comment by barnybug** [comment]
Thanks for this - any chance you could add a test case to the existing tests? thanks

**Comment by ankon** [comment]
I tried adding some tests -- I'm not that used to python or the testing environment though.

The good news is that the tests as-such did show two other errors :)
1. 3083d8a fixes another copy-paste error
2. abc2fd5 changes the conditions for EvaluateTargetHealth, otherwise AWS refuses to create the records.

**Comment by barnybug** [comment]
Great, thanks for this. I made a couple of small tweaks, otherwise all good.

**Comment by ankon** [comment]
Thanks a lot!

**Pull request merged**
