### PR TITLE
update

### PR DESCRIPTION
**Pull request by anmolnagpal**
Please when making a pull request:

- check code has been go formatted with 'go fmt'.
- ensure you've added an integration test (under internal/features) or a unit test.
- check the tests pass (make test).

cli53 has very good existing test coverage, so I'm unlikely to accept a pull request without
a test, but please do ping me if you're struggling to add a test case and I'll help!

### CODE REVIEW

**Comment by barnybug** [comment]
?

**Comment by barnybug** [comment]
Thanks for your contribution! We'll triage and take a look at it as soon as possible!

**Comment by barnybug** [comment]
Hi - I've manually added these lines to the README, thanks.

Just for the future:
- commit message should be descriptive (not 'update'!)
- should be based off latest master (this was out of date)
- indentation should be consistent (it used spaces, not tabs)

**Comment by anmolnagpal** [comment]
Oke,

Will take of this in future.

Thanks
A

On Thursday, 31 March 2016, Barnaby Gray <notifications@github.com> wrote:

> Hi - I've manually added these lines to the README, thanks.
>
> Just for the future:
>
>    - commit message should be descriptive (not 'update'!)
>    - should be based off latest master (this was out of date)
>    - indentation should be consistent (it used spaces, not tabs)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/barnybug/cli53/pull/165#issuecomment-204046274>
>


-- 
-- 
Anmol Nagpal
DevOps Engineer

Phone: +971 56 1794179
Whatsapp: +919316644334
Skype: anmolnagpaul

**Pull request closed without merging**
