### PR TITLE
new cmd: validate zone file only

### PR DESCRIPTION
**Pull request by mrozentsvayg**
for the zone control automation (CI), built on top of `cli53`, normally `import --dry-run` is used to as a validation step for the changes in the zones.
however, if the zone doesn't exist yet, the separate ~~`parse`~~ `validate` command could be very useful to avoid cumbersome workarounds.

### CODE REVIEW

**Comment by barnybug** [comment]
Looks good - though I think 'validate' might be a better name for the command.

**Comment by mrozentsvayg** [comment]
> Looks good - though I think 'validate' might be a better name for the command.

it really is, PR updated

**Comment by mrozentsvayg** [comment]
@barnybug i've tried to manually reproduce the exact steps taken by the [failed action](https://github.com/barnybug/cli53/runs/5657877334?check_suite_focus=true) for the [workflow](https://github.com/barnybug/cli53/actions/runs/2027521494/workflow) on fresh focal vm, and it worked fine.
```
root@focal:~/go/src/github.com/barnybug/cli53# make test-coverage
go get github.com/wadey/gocovmerge
go get github.com/gucumber/gucumber/cmd/gucumber
go: found github.com/gucumber/gucumber/cmd/gucumber in github.com/gucumber/gucumber v0.0.0-20180127021336-7d5c79e832a2
rm -rf coverage && mkdir coverage
go test -covermode=count -coverprofile=coverage/unit.txt
PASS
coverage: 26.4% of statements
ok      github.com/barnybug/cli53       0.008s
go test -c -covermode=count -coverpkg . -o ./cli53 ./cmd/cli53
COVERAGE=1 gucumber -tags=@validate
@validate
Feature: validate a zone file syntax
  Scenario: correct zone file validation succeeds               # internal/features/validate.feature:2
    When I execute "cli53 validate --file tests/validate1.txt"  # internal/features/validate.feature:3
    Then the exit code was 0                                    # internal/features/validate.feature:4

  Scenario: incorrect zone file fails validation                # internal/features/validate.feature:5
    When I execute "cli53 validate --file tests/validate2.txt"  # internal/features/validate.feature:6
    Then the exit code was 1                                    # internal/features/validate.feature:9

Finished (4 passed, 0 failed, 0 skipped).

gocovmerge coverage/*.txt > coverage.txt
root@focal:~/go/src/github.com/barnybug/cli53#
```

any ideas why the action has failed, or should I try to reproduce the action in my fork?

**Comment by barnybug** [comment]
Had noticed - will take a look when I get some time.

**Comment by SaveTheRbtz** [comment]
[Looking at the output](https://github.com/barnybug/cli53/runs/5882074364?check_suite_focus=true) from #321:

```
Exit code expected: 0 != actual: 1. Output: PASS
coverage: 5.6%!o(MISSING)f statements in .
```

Seems like 1 is returned not by the cli53 binary itself, but whatever code is added by the:
https://github.com/barnybug/cli53/blob/2fa9106122b6ea01e97e5c924fbeab64c0466dcf/Makefile#L32
(likely one of the defer functions in the `testing` package)

Anyway, I would propose:
* bumping go version to a more stable version.
* bumping the [setup go action](https://github.com/actions/setup-go) version to v3.
* enabling actions on pull requests as well as on pushes.
* setting up dependabot to keep deps up-to-date.

If this does not help, we can look into the coverage report to see where it abruptly ends calling `os.Exit(1)` or try `strace`ing the binary.

**Pull request merged**
